stages:
  - build
  - singularity

build-docker:
  image: docker:stable
  stage: build
  before_script:
    - apk add git openssh make bash
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
    - bash urls.sh
    - git submodule update --init
      #    - (cd dda-interface-app/)
  script:
    - make build
    - make push
  only:
    - staging-1.3
    - ci

build-singularity:
  image: docker:stable
  stage: singularity
  before_script:
    - apk add git openssh make bash
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
  script:
    - make singularity
  only:
    - staging-1.3
    - ci


#trigger_deployment:
#  stage: .post
#  trigger:
#    project: cdci/dispatcher/dispatcher-chart
#    branch: staging-1.3

#  only:
#    - staging-1.3
#    - ci
